name: "Ian Sequeira"
email: "iesequeira34@gmail.com"
pic: "profile-pic-small.PNG"

description: |
  Machine Learning Engineer building scalable, agentic AI systems using LLMs,
  reinforcement learning, and multimodal models. Experienced in deploying
  Generative AI solutions for NLP, vision, and structured data tasks.
  Focused on aligning ML with business goals.

skills:
  - name: "Python"
    icon: "python.png"

  - name: "PyTorch"
    icon: "pytorch.png"

  - name: "Docker"
    icon: "docker.png"

  - name: "Kubernetes"
    icon: "kubernetes.png"

  - name: "C++"
    icon: "cpp.png"

  - name: "FastAPI"
    icon: "fastapi.png"

  - name: "Langgraph"
    icon: "langgraph.png"

  - name: "MLFlow"
    icon: "mlflow.png"

  - name: "PineCone"
    icon: "pinecone.png"

  - name: "PowerBI"
    icon: "powerbi.png"

  - name: "Scikit-Learn"
    icon: "scikitlearn.png"

  - name: "Azure Cloud Services"
    icon: "azure.png"

socials:
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/ian-sequeira-94b924204/"
    icon: "linkedin-logo.png"

  - name: "GitHub"
    link: "https://github.com/iesequeira34"
    icon: "github-icon.png"

  - name: "Email"
    link: "mailto:iesequeira34@gmail.com"
    icon: "email-icon.png"

  - name: "Phone"
    link: "tel:+919769007256"
    icon: "phone-icon.png"

